# AUTOGENERATED BY NBDEV! DO NOT EDIT!

__all__ = ["index", "modules", "custom_doc_links", "git_url"]

index = {"base_key": "00_generator.ipynb",
         "table_name": "00_generator.ipynb",
         "api_key": "00_generator.ipynb",
         "promoters": "00_generator.ipynb",
         "terminators": "00_generator.ipynb",
         "conc": "00_generator.ipynb",
         "plasmida": "00_generator.ipynb",
         "airtable": "00_generator.ipynb",
         "names": "00_generator.ipynb",
         "seqIDs": "00_generator.ipynb",
         "pandaframe": "00_generator.ipynb",
         "selector_maker_2": "00_generator.ipynb"}

modules = ["generator.py"]

doc_url = "https://fregat17.github.io/auto_seq_req/"

git_url = "https://github.com/fregat17/auto_seq_req/tree/master/"

def custom_doc_links(name): return None
