# AUTOGENERATED! DO NOT EDIT! File to edit: 00_generator.ipynb (unless otherwise specified).

__all__ = ['base_key', 'table_name', 'api_key', 'promoters', 'terminators', 'conc', 'plasmida', 'airtable', 'names',
           'seqIDs', 'pandaframe', 'selector_maker_2']

# Cell
import os
from airtable import airtable
import numpy as np
import pandas as pd
import xlsxwriter
import collections

# Cell
base_key = os.environ['AIR_BASE_KEY']
table_name = 'Cloning reactions'
api_key = os.environ['AIR_API_KEY']

promoters = {'CMV':'c1for2',
             'hPGK':'PGK F',
             'PGK':'PGK F',
             'EF1':'EF1 F',
             'CAG':None,
             'pCAG':None,
             'SV40':'SV40 F'}

terminators = {'SV40':'c1rev2',
               'BGH':'BGH R',
               'rbGlob':'G R',
               'PGK':'PGK R'}

conc = "5 mkM"

plasmida = "Plasmid"

# Cell
airtable = airtable.Airtable(base_key, api_key=api_key)

# Cell
names = []
seqIDs = []

for r in airtable.iterate(table_name):
    if r['fields']:
        names.append(r['fields']['Name'])
        seqIDs.append('{:.2f}'.format(r['fields']['SeqID']))

pandaframe = pd.DataFrame({'Name':names, 'SeqID': seqIDs}).round(decimals=2)

# Cell
def selector_maker_2(start, end):
    return ['{:.2f}'.format(x) for x in np.arange(start,end+0.01, 0.01)]